/* This file is autogenerated.  Do not edit */

#include <liboil/liboilfunction.h>

OilFunctionClass *_oil_function_class_array[] = {
  NULL
};

OilFunctionImpl *_oil_function_impl_array[] = {
  NULL
};

