#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_LRINTF 1
#define HAVE_SINF 1
#define HAVE_COSF 1
#define HAVE_LOGF 1
#define HAVE_EXPF 1
#define HAVE_FLOORF 1
#define HAVE_CEILF 1
#define HAVE_SQRTF 1
